export interface Company {
    lm_company_id:number;
    name : string,
    description: string,
    location: string,
    phone_no: number,
    alt_phone_no: number,
    address: string,
    city: string,
    state: string,
    country: string,
    postal_code: string,
    email: string,
    revenue: number,
    lm_contact_company_id: number,
    lm_sales_status_id: number,
    ddo_client_id: number,
    ddo_org_id: string,
    createdAt: Date,
    updatedAt: Date,
    updated_by: number,
    created_by: number,
    isactive: boolean,
    updated: Date,
    created: Date,
    industry:  string,
    no_of_people: number,

    }
