export interface ContactImports {
    lm_contact_imports_id:number,
    file_name : string,
    uploaded_by: string,
    purpose: String,
    ddo_client_id: number,
    ddo_org_id: number,
    created_by: number,
    updated_by: number,
    isactive: boolean,
    created:string,
    updated: string,
    array_data:any,
    contacttype :any,
    salesstatustype:any,
}
